#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db
#    username: user
#    password: pass
#    hikari:
#      driverClassName: org.postgresql.Driver
#
spring:
  datasource:
    url: jdbc:h2:mem:sampledb
    username: user
    password: pass
    hikari:
      driverClassName: org.h2.Driver